### ISSUE TITLE
Question on Performance

### ISSUE THREAD

**Issue by kevinroberts** [caprica/vlcj-javafx#1]
Hi Caprica Team,

First of all, I love your plugin and if this is more appropriate for a StackOverflow question let me know. I will not be offended if you remove this.

I have been working on a JavaFX application I'm calling Gif Vault in my spare time. The idea is to display a Grid View of a bunch of MP4 files looped from various Gif providers. The application uses VLCj's EmbeddedMediaPlayer to display the files and I'm playing about 20 of them in a grid. 
The problem is when I try to switch views the performance really struggles; as in my 2019 MacBook Pro grinds to a halt for a couple of seconds and I do have an occasional java process crash. I am releasing the video resources for each player before switching views. The main thing I want to know is if this is a feasible use case for this plugin or not? I saw the windows version might offer better performance and I haven't tried it on that platform yet.
Using Java 11.0.2,  'vlcj-javafx', version: '1.0.2'

Example interface:
<img width="1103" alt="Screen Shot 2020-05-23 at 11 22 47 AM" src="https://user-images.githubusercontent.com/188386/83074100-39b48a00-a037-11ea-9496-f83f4b0c29c2.png">

**Comment by caprica** [comment]
You've seen this project presumably: https://github.com/caprica/vlcj-javafx-demo

Make sure you are using the PixelBuffer solution with JavaFX 13+.

In my demo project I can play, on a pretty old iMac, 9 *concurrent* HD videos without any problem.

If I push it to 12 *concurrent* media players I do start to see slowdown.

So in general terms, this seems good enough to me for a performance baseline.

For your own application, are you creating a new media player for each item in your grid? Do you play one video at a time or do you want multiple media players playing concurrently?

There is a big difference in resource usage from having a grid of 400 items with 400 media players vs a grid with 400 items and 1 media player that you can reassign to the currently selected video.

So without knowing much more about your application, I would recommend (assuming one video at a time) that you have a single media player instance and when you click one of your videos you reassign your media player to the selected component - this component would display either the thumbnail like your screenshot, or the media player video surface.

The key thing here is to have a single media player that you reuse.

From what you've posted, and I know I made assumptions, that's all I can suggest.

I have seen performance issues and stalls, not with vlcj's media players, but with JavaFX's grid view and having lots of items in the grid. If this is relevant to your application, maybe you need to virtualise that grid.

I will also add I have *never* seen vlcj on JavaFX hard-crash the JVM, so either you are hitting a native resource limit, or you're not keeping hold of your media player correctly and it's being garbage collected.

**Comment by caprica** [comment]
Also, it's generally a better idea to keep and re-use a media player instance rather than throwing it away each time you select/play new media.

Releasing the native resources associated with a media player shouldn't be an issue, but unfortunately sometimes it can be - so IMO it's always best to mitigate such potential problems by keeping and reusing those media players.

**Comment by kevinroberts** [comment]
Thanks so much for the response and thoughts. I will try rearchitecting the players and grid, limit the number of playing videos down, and re-use the player instead of releasing and creating new instances. I can follow up with a performance update if interested, the code is all open-sourced as well.

**Comment by caprica** [comment]
So you were playing multiple videos concurrently? If so, at some point you would hit a resource limit so putting some bounds on the number of concurrent players would be a good idea. Clearly now IMO you should use a pool of reusable media players and switch them around as needed, without destroying and recreating them.

Unfortunately only empirical testing will tell you how many concurrent players you can get away with, or punt it to the user with a setting.

By all means if you want to post your own resolution here I'm not going to object. I may close the issue in the meantime however as I don't like being nagged by open issues in my inbox. :-)

**Comment by kevinroberts** [comment]
Makes sense! Yup no worries.
