### ISSUE TITLE
How do I use multiple windows or show FileChooser and vlcj in Ubuntu 15.10

### ISSUE THREAD

**Issue by iRipVanWinkle** [caprica/vlcj-javafx#10]
How do I use multiple windows or show FileChooser and vlcj in Ubuntu 15.10
When I trying open FileChooser my app showing error.
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc6b2790c84, pid=6059, tid=140489591023360
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libpthread.so.0+0x9c84]  pthread_mutex_lock+0x4
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by caprica** [comment]
So are there two separate questions here or one?

Given what little you've posted, how much help do you really expect?!

**Comment by iRipVanWinkle** [comment]
I am sorry. I was angry, because I have tried many options and all thrown error.
I understood that this error in thread, but I but I do not know how to fix it.

 I used code from this repository, and added FileChooser https://github.com/iRipVanWinkle/vlcj-javafx/blob/master/src/test/java/uk/co/caprica/vlcj/javafx/test/resize/ResizableJavaFXPlayerTest.java

And this short code does not work:
```
import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.BorderPane;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.direct.DirectMediaPlayer;
import uk.co.caprica.vlcj.player.direct.format.RV32BufferFormat;

public class Main extends Application {

    private static final String PATH_TO_VIDEO = "/home/iripvanwinkle/Videos/How fast.ogg";

    private final DirectMediaPlayer directMediaPlayer;

    public Main() {
        directMediaPlayer = (new MediaPlayerFactory())
                .newDirectMediaPlayer(RV32BufferFormat::new, (mediaPlayer, nativeBuffers, bufferFormat) -> {
                });
    }

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {

        Button button = new Button("Show FileChooser");
        button.setOnAction((event) -> {
            FileChooser fileChooser = new FileChooser();
            fileChooser.showOpenMultipleDialog(primaryStage);
        });

        primaryStage.setTitle("EWF");
        primaryStage.setScene(new Scene(new BorderPane(button), 1270, 600));

        primaryStage.setOnCloseRequest(event -> {
            Platform.exit();
            System.exit(0);
        });

        primaryStage.show();

        directMediaPlayer.prepareMedia(PATH_TO_VIDEO);
        directMediaPlayer.start();
    }
}
``` 
Sometimes error shows: 
```
java: tpp.c:84: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.
```

But in Windows is all OK.

This problem in Ubuntu or vlcj or vlc? And how fix it.
Maybe the bug only my.

**Comment by caprica** [comment]
Which line of code triggers the JVM crash?

What happens if you don't use vlcj?

**Comment by iRipVanWinkle** [comment]
**1**
JVM crash on line:
```
fileChooser.showOpenMultipleDialog(primaryStage);
```
more in javafx.stage.FileChooser:
```
private List<File> showDialog(final Window ownerWindow,
                                  final FileChooserType fileChooserType){
FileChooserResult result = Toolkit.getToolkit().showFileChooser(
                (ownerWindow != null) ? ownerWindow.impl_getPeer() : null,
                getTitle(),
                getInitialDirectory(),
                getInitialFileName(),
                fileChooserType,
                extensionFilters,
                getSelectedExtensionFilter());
....
}
```
Crash when  Toolkit.getToolkit().showFileChooser() returned value.
If I create DirectMediaPlayer in constructor Main() and won't use DirectMediaPlayer in the method start(). I will not have crash.
In other cases I have crashes.

Sometimes not crash, bat this hardly ever.

Crash logs:
https://github.com/iRipVanWinkle/vlcj-javafx-crash/blob/master/hs_err_pid5945.log
https://github.com/iRipVanWinkle/vlcj-javafx-crash/blob/master/hs_err_pid6114.log

This is my test app:
https://github.com/iRipVanWinkle/vlcj-javafx-crash/tree/master/src/test/java/test

**2**
If I not used vlcj, when i click in button i see File Chooser dialog and my app  worked.

**Comment by caprica** [comment]
I don't see any code to actually render your video.

Also, what happens if you do directMediaPlayer.playMedia(...) instead of using prepareMedia() and start().

**Comment by caprica** [comment]
This might be something specific to the file chooser. I tried with a standard JavaFX Alert dialog and that worked just fine.

**Comment by caprica** [comment]
There must be a race condition somewhere, because if I step through in a debugger (deep into the JavaFX code in fact) I can get the file chooser to appear without crashing.

![screenshot from 2015-12-10 22 09 46](https://cloud.githubusercontent.com/assets/1385879/11730117/dd161fe0-9f8a-11e5-8919-8762fe68d9d9.png)

**Comment by caprica** [comment]
Unfortunately, I don't know...

**Comment by iRipVanWinkle** [comment]
What your Linux distribution and java?

I run on Ubuntu 15.10x64, 15.10x32, 14.10x64 and Oracle Java 8_66. And I install clear OS, vlc and java. And i have crash :(

**Comment by caprica** [comment]
I use Linux Mint 17.2, 64-bit, and Oracle JDK 1.8.0_60.

But to be clear, this does not actually work for me - it only works if I single step the JavaFX code in a debugger. So there must be a race condition somewhere.

**Comment by iRipVanWinkle** [comment]
I run application used Linux Mint 17.2, 64-bit, and Oracle JDK 1.8.0_66 and crash again :(
I do not know what to do?

**Comment by caprica** [comment]
Unfortunately I don't know either. There is some race condition in play here, and maybe some combination of LibVLC/vlcj's native threading and whatever the JavaFX file chooser is doing. This is most likely to be a native crash and will be very difficult to find out what's going on.

**Comment by iRipVanWinkle** [comment]
I added to JVM option -DVLCJ_INITX=no and all ok

**Comment by caprica** [comment]
Excellent, thanks for reporting your fix.
