### ISSUE TITLE
Lag when resize video

### ISSUE THREAD

**Issue by seravifer** [caprica/vlcj-javafx#13]
When you resize the window, the video takes a long time to resize, with a lot of lag. Is there any way that it will not appreciate or function properly?

**Comment by seravifer** [comment]
I fixed it by changing the `fitImageViewSize` method by this:
```
imageView.fitWidthProperty().bind(playerHolderID.widthProperty());
imageView.fitHeightProperty().bind(playerHolderID.heightProperty());
imageView.setPreserveRatio(true);
```
Now the only problem is that it is not focused.
Solution, convert `playerHolderID` to an `HBox` and center it.
It is now much smoother resizing but you can see a small lag.

**Comment by caprica** [comment]
I appreciate this response is very late, but thanks for the tip.

In any case, resize needs to be reworked as per #16.
