### ISSUE TITLE
displaying video using swing node and jpanel

### ISSUE THREAD

**Issue by sjaiswal25** [caprica/vlcj-javafx#14]
Is it not possible to access the video using the following method?

`import javax.swing.*;
import javafx.application.Application;
import javafx.embed.swing.SwingNode;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;
import uk.co.caprica.vlcj.discovery.NativeDiscovery;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;

import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;

public class SwingNodeExample extends Application {
    
    private final String rtsp_path = "rtsp_path";
    @Override
    public void start(Stage stage) {
        final SwingNode swingNode = new SwingNode();
        createAndSetSwingContent(swingNode);

        Pane pane = new Pane();
        pane.getChildren().add(swingNode); // Adding swing node

        stage.setScene(new Scene(pane, 100, 50));
        stage.show();
    }

    private void createAndSetSwingContent(final SwingNode swingNode) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                final EmbeddedMediaPlayerComponent mediaPlayerComponent;
                JPanel jpanel = new JPanel();
                mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
                jpanel.add(mediaPlayerComponent);
                //panel.add(new JButton("Click me!"));
                swingNode.setContent(jpanel);
            }
        });
    }

    public static void main(String[] args) {
        launch(args);
    }
}`

**Comment by caprica** [comment]
No. JavaFX is lightweight and can't reliably embed a heavyweight AWT Canvas.
