### ISSUE TITLE
MediaPlayer play error callback?

### ISSUE THREAD

**Issue by zoyaforever** [caprica/vlcj-javafx#19]
Hi

After I call mediaPlayer.media().play(VIDEO_FILE), is there any way to be notified when play fails?
eg.

1. Network bad
2. File not exists

Thanks.

**Comment by caprica** [comment]
Unfortunately no, not really. Either the initial play media call will return false, or if the media failed to start there will be an error callback on the media player event listener. But if something like a network disconnect happens you won't be notified of any error.
