### ISSUE TITLE
JRE crashing

### ISSUE THREAD

**Issue by fearchannel** [caprica/vlcj-javafx#24]
When I'm executing my class (based on WritableImageDemo.java), I'm having an JVM crash. There is something wrong?

.log:
https://pastebin.com/rTyQ2JLZ

The only thing that is different from the example is that program initialization was externalized into a main class:

```
public class Main extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        new Player().start(primaryStage);
    }
}
```

and the player.class:

```
public class Player{

    private MediaPlayerFactory mediaPlayerFactory;

    private EmbeddedMediaPlayer mediaPlayer;

    private PixelBuffer<ByteBuffer> videoPixelBuffer;

    private WritableImage videoImage;

    private ImageView videoImageView;

    public Player() {
        mediaPlayerFactory = new MediaPlayerFactory();
        mediaPlayer = mediaPlayerFactory.mediaPlayers().newEmbeddedMediaPlayer();
        mediaPlayer.videoSurface().set(new FXCallbackVideoSurface());
    }

    public void start(Stage primaryStage) {
        StackPane root = new StackPane();
        root.setStyle("-fx-background-color: black;");
        videoImageView = new ImageView();
        videoImageView.setPreserveRatio(true);
        videoImageView.fitWidthProperty().bind(root.widthProperty());
        videoImageView.fitHeightProperty().bind(root.heightProperty());
        root.getChildren().add(videoImageView);


        Scene scene = new Scene(root, 1200, 675);
        primaryStage.setScene(scene);
        primaryStage.show();

        String mrl = "file";

        mediaPlayer.media().play(mrl);
    }
_[...]_
```

**Comment by fearchannel** [comment]
I noticed this: While opening the connection, it comes out in the output. I don't know if it will help, but I hope so:

> (java:7037): Gdk-WARNING **: 15:33:01.681: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
> Created new TCP socket 49 for connection
> Created new TCP socket 49 for connection
> JNA: callback object has been garbage collected
> JNA: callback object has been garbage collected
> JNA: callback object has been garbage collected

**Comment by caprica** [comment]
You can ignore the GDK warning.

Anyway, the pertinent messages are telling you something has been unexpectedly garbage collected.

Most likely it's because of this:
```
public void start(Stage primaryStage) {
    new Player().start(primaryStage);
}
```
This start() method allocated a new Player() instance on the heap. When the start method returns, that Player instance is no longer reachable (nothing is keeping a reference to it) so it becomes eligible for garbage collection. Some indeterminate time later the object gets garbage collected, and your application crashes (because LibVLC is trying to call back into your Java object).

This is sadly a very common error, no matter how many warnings I write in READMEs, Javadoc or tutorials.

The solution is keep a hard reference to your objects.

**Comment by fearchannel** [comment]
Hi, @caprica. I read that could be it, but even keeping a hard reference the error is the same

**Comment by caprica** [comment]
There is no other explanation for this message:
```
JNA: callback object has been garbage collected
```
Something in your code has been garbage collected that should not have been. You will have to try and track down which object.

**Comment by fearchannel** [comment]
I'm still implementing it, but I don't see anything that can be eligible for GC. Can it be these inner class?

```
public class Player {

    private MediaPlayerFactory mediaPlayerFactory;

    private EmbeddedMediaPlayer mediaPlayer;

    private PixelBuffer<ByteBuffer> videoPixelBuffer;

    private WritableImage videoImage;

    private ImageView videoImageView;

    public Player() {
        mediaPlayerFactory = new MediaPlayerFactory();
        mediaPlayer = mediaPlayerFactory.mediaPlayers().newEmbeddedMediaPlayer();
        mediaPlayer.videoSurface().set(new FXCallbackVideoSurface());
    }

    public void iniciar(Stage primaryStage) {
        StackPane root = new StackPane();
        root.setStyle("-fx-background-color: black;");
        videoImageView = new ImageView();
        videoImageView.setPreserveRatio(true);
        videoImageView.fitWidthProperty().bind(root.widthProperty());
        videoImageView.fitHeightProperty().bind(root.heightProperty());
        root.getChildren().add(videoImageView);

        Scene scene = new Scene(root, 1200, 675);
        primaryStage.setScene(scene);
        primaryStage.show();

        String mrl = "rtsp://admin:kgb8y2@177.129.0.47:555/mode=real&idc=1&ids=1";

        mediaPlayer.media().play(mrl);
    }

    private class FXCallbackVideoSurface extends CallbackVideoSurface {
        FXCallbackVideoSurface() {
            super(new FXBufferFormatCallback(), new FXRenderCallback(), true, VideoSurfaceAdapters.getVideoSurfaceAdapter());
        }
    }

    private class FXBufferFormatCallback implements BufferFormatCallback {
        private int sourceWidth;
        private int sourceHeight;

        @Override
        public BufferFormat getBufferFormat(int sourceWidth, int sourceHeight) {
            this.sourceWidth = sourceWidth;
            this.sourceHeight = sourceHeight;
            return new RV32BufferFormat(sourceWidth, sourceHeight);
        }

        @Override
        public void allocatedBuffers(ByteBuffer[] buffers) {
            assert buffers[0].capacity() == sourceWidth * sourceHeight * 4;
            PixelFormat<ByteBuffer> pixelFormat = PixelFormat.getByteBgraPreInstance();
            videoPixelBuffer = new PixelBuffer<>(sourceWidth, sourceHeight, buffers[0], pixelFormat);
            videoImage = new WritableImage(videoPixelBuffer);
            videoImageView.setImage(videoImage);
        }
    }

    private class FXRenderCallback implements RenderCallback {
        @Override
        public void display(MediaPlayer mediaPlayer, ByteBuffer[] nativeBuffers, BufferFormat bufferFormat) {
            Platform.runLater(() -> {
                videoPixelBuffer.updateBuffer(pb -> null);
            });
        }
    }
}
```

**Comment by caprica** [comment]
The code you've posted is basically the same as the provided WritableImageDemo. The problem is very unlikely to be in there since that code works.

The onus is on you here really, you have a fully working example to compare against.

**Comment by fearchannel** [comment]
Thanks for the help! I'm trying to make it work, and if the code is pretty much the same, I thought it would work normally. I don't know what may be happening here

**Comment by caprica** [comment]
Are you absolutely sure the Player instance, and the thing that creates the Player instance are being properly pinned by hard references?

**Comment by fearchannel** [comment]
the thing that creates the player instance is my main method, so I don't think that it is he. And Player instance is just as you told me

**Comment by caprica** [comment]
But are you *sure*?!

Maybe post your main class...

**Comment by fearchannel** [comment]
```
public class Main extends Application {

    @Override
    public void start(Stage primaryStage) throws IOException {
        Player player = new Player();
        player.iniciar(primaryStage);
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

**Comment by caprica** [comment]
This part:
```
@Override
    public void start(Stage primaryStage) throws IOException {
        Player player = new Player();
        player.iniciar(primaryStage);
    }
```
You create a new Player() instance in this method, and it immediately goes out of scope and becomes eligible for garbage collection.

Keep a reference to that player instance at class level.

**Comment by fearchannel** [comment]
I was using the following code to generate a player:
    
```
    MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory();
        EmbeddedMediaPlayer mediaPlayer = mediaPlayerFactory.mediaPlayers().newEmbeddedMediaPlayer();
        mediaPlayer.media().play(mrl,options);
```

This has been a while. Since then, I've changed JDK (8> 11) and JavaFX (11> 13). I have now tested this code and it also constantly speaks:

> JNA: Callback Object has been garbage collected

This message only appears when using VLCj. Maybe this info is useful...

**Comment by caprica** [comment]
Your last comment, it really is not much use to post isolated code fragments like that. Because those three lines you've posted are either potentially OK, or two of those lines have critical errors. But because you've not posted them *in context*, it's impossible to say.

I already explained the JNA callback message. There is no other explanation.

**Comment by fearchannel** [comment]
Sorry. I thought it might help, but what you said makes more sense. I will try to improve my reports here. Once again, I'm sorry. Thank you for helping me so far. By the way, keeping Player at class level solved it.

**Comment by caprica** [comment]
Don't be sorry.

My original answer was right, I just needed to convince you :-)

**Comment by fearchannel** [comment]
And you did it. I just needed to understand, really. Thank you, Mark! Have a great day.

**Comment by rahulaparajit79** [comment]
Hi, I am having the same issue. I am using javafx. Is this crash due to javafx ?
@fearchannel  It seems you also used javafx. Could you please help me fixing the issue ?

**Comment by fearchannel** [comment]
Hello, @rahulaparajit79.

I guess I solved it by using Platform.runLater. Try it! (:

**Comment by caprica** [comment]
This issue was all about not keeping references to vlcj objects, some basic principles are here http://capricasoftware.co.uk/projects/vlcj-4/tutorials/garbage-collection.

It is possible you are crashing for different reasons, but by far the most common cause of crashes with vlcj is application developers not keeping hold of vlcj objects and letting them be garbage collected.

**Comment by rahulaparajit79** [comment]
`
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.binding.internal.libvlc_media_t;
import uk.co.caprica.vlcj.binding.internal.libvlc_state_t;
import uk.co.caprica.vlcj.component.DirectMediaPlayerComponent;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.discovery.NativeDiscovery;
import uk.co.caprica.vlcj.player.MediaPlayerEventListener;
import uk.co.caprica.vlcj.player.direct.BufferFormat;
import uk.co.caprica.vlcj.player.direct.BufferFormatCallback;
import uk.co.caprica.vlcj.player.direct.DefaultDirectMediaPlayer;
import uk.co.caprica.vlcj.player.direct.format.RV32BufferFormat;
import uk.co.caprica.vlcj.player.media.Media;
import uk.co.caprica.vlcj.player.media.callback.AbstractCallbackMedia;
import uk.co.caprica.vlcj.player.media.callback.seekable.RandomAccessFileMedia;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

public class PlayerController implements Initializable, PlayerState {

    private DirectMediaPlayerComponent mediaComponent;
    private MediaPlayer mediaPlayer;
    private AnimationTimer timer;
    private WritableImage vidImage;
    private PixelWriter pixelWriter;
    private WritablePixelFormat<ByteBuffer> byteBgraInstance;
    private double imgWidth;
    private double imgHeight;
    private double mediaPlayerLength = 0;

@Override
    @EnvelopeMethodProtectionAttributes(Protect = false)
    public void initialize(URL url, ResourceBundle rb) {

        lblPlayerTitle.setText(APIConstants.PLAYER_TITLE);

        initProcessDialogCallback();
        playPauseVisibleDisable();
        labelShowHide();
        toolTipText();
//        alertLabel.setVisible(false);
//        maximizeScreen.setVisible(true);
//        minimizeScreen.setVisible(false);

        rightgrid.setVisible(false);
        leftgrid.setVisible(false);
//        bottomGrid.setVisible(false);

        getStudentDetails();
        comboboxSetData();
        videoListViewListners();
        courseComboboxListners();
        bookmarkListViewListners();
        setMediaViewWidthHeight();
        setMediaTimerOnSync();
        btnUpdateListners();
        btnV2CListners();
        initSeekSlider();
        initJettyErrorCallback();
        initSpeedCombobox();
        initLectureInfoListner();
//        initMediaMouseMoveListner();

        imgWidth = mediaView.getFitWidth();
        imgHeight = imgWidth / 1.78;
        vidImage = new WritableImage((int) imgWidth, (int) imgHeight);
        mediaView.setImage(vidImage);
        initMediaComponents();
        initTimer();
    }
@Override
    public void playerInitialize() {
        Platform.runLater(new Runnable() {
            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void run() {
                setPlayPleaseWaitVisible();
            }
        });

        if (mediaPlayer != null) {
            mediaPlayer.stop();
        }
//        initMediaComponents();
        studentLectureRemainingTime = selectedLecture.getStudentLectureRemainingTime();
//        String path = new File(absolutePathOfBowsedFile + "/" + selectedLectureVideo).getAbsolutePath();
        String path = new File(filePathMap.get(selectedLectureVideo)).getAbsolutePath();
        EmbeddedServer.gdtfp(path, new EmbeddedServer.IPathReady() {
            @EnvelopeMethodProtectionAttributes(Protect = false)
            @Override
            public void onPathReady(String path) {
                try {
                    lecturePath = new String(path);
                    Platform.runLater(new Runnable() {
                        @Override
                        @EnvelopeMethodProtectionAttributes(Protect = false)
                        public void run() {
//                            Media media = new MyRandomAccessFileMedia(new File(path));
//                            Media media = new RandomAccessFileMedia(new File(path));

                            mediaPlayer.startMedia(lecturePath);
                            mediaPlayer.setVolume(100);
                            mediaPlayer.pause();

                            mediaPlayerLength = (double) mediaPlayer.getLength();

                            if (borderPane.getChildren().indexOf(leftgrid) == -1) {
                                borderPane.getChildren().add(leftgrid);
                            }
                            leftgrid.setVisible(true);
                            hiddenLeftPane = false;
                            leftgrid.setVisible(false);
                            borderPane.getChildren().remove(leftgrid);
                            hiddenLeftPane = true;

                            if (borderPane.getChildren().indexOf(rightgrid) == -1) {
                                borderPane.getChildren().add(rightgrid);
                            }
                            rightgrid.setVisible(true);
                            hiddenRightPane = false;
                            rightgrid.setVisible(false);
                            borderPane.getChildren().remove(rightgrid);
                            hiddenRightPane = true;

                            cmbSpeed.getSelectionModel().select("1.0x");
                            setPlayPleaseWaitDisable();
                            scrollingText();

                            initializeVolumeSlider();

                        }
                    });
                } catch (MediaException ex) {
                    logger.log(Level.SEVERE, ex.getMessage(), ex);
                    setPlayPleaseWaitDisable();
                    videoListView.getSelectionModel().clearSelection();
                    AlertDialog.showError("Unable to play lecture. Please check your selected course.");
                }

            }

            @Override
            public void onFailure(String msg) {
                setPlayPleaseWaitDisable();
                scrollingText();
                AlertDialog.showError(msg);
            }
        });

        //fit to screen mediaview..
        DoubleProperty width = mediaView.fitWidthProperty();
        DoubleProperty height = mediaView.fitHeightProperty();
        width.bind(Bindings.selectDouble(mediaView.sceneProperty(), "width"));
        height.bind(Bindings.selectDouble(mediaView.sceneProperty(), "height"));
        mediaView.setPreserveRatio(true);
    }
private static final double FPS = 25.0;

    private final NanoTimer nanoTimer = new NanoTimer(1000.0 / FPS) {
        @Override
        @EnvelopeMethodProtectionAttributes(Protect = false)
        protected void onSucceeded() {
            renderFrame();
        }
    };

    protected final void renderFrame() {
        Memory[] nativeBuffers = mediaComponent.getMediaPlayer().lock();
        if (nativeBuffers != null) {
// FIXME there may be more efficient ways to do this...
// Since this is now being called by a specific rendering time, independent of the native video callbacks being
// invoked, some more defensive conditional checks are needed
            Memory nativeBuffer = nativeBuffers[0];
            if (nativeBuffer != null) {
                ByteBuffer byteBuffer = nativeBuffer.getByteBuffer(0, nativeBuffer.size());
                BufferFormat bufferFormat = ((DefaultDirectMediaPlayer) mediaComponent.getMediaPlayer()).getBufferFormat();
                if (bufferFormat.getWidth() > 0 && bufferFormat.getHeight() > 0) {
                    pixelWriter.setPixels(0, 0, bufferFormat.getWidth(), bufferFormat.getHeight(), byteBgraInstance, byteBuffer, bufferFormat.getPitches()[0]);
                }
            }
        }
        mediaComponent.getMediaPlayer().unlock();
    }

 public void initMediaComponents() {
//        boolean found = new NativeDiscovery().discover();
//        System.out.println(found);
//        System.out.println(LibVlc.INSTANCE.libvlc_get_version());
        NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), System.getProperty("user.dir") + "/libvlc");

        pixelWriter = vidImage.getPixelWriter();
        byteBgraInstance = PixelFormat.getByteBgraPreInstance();

        mediaComponent = new DirectMediaPlayerComponent(new BufferFormatCallback() {

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public BufferFormat getBufferFormat(int sourceWidth, int sourceHeight) {
                return new RV32BufferFormat((int) imgWidth, (int) imgHeight);
            }
        });
        mediaPlayer = mediaComponent.getMediaPlayer();
        mediaPlayer.setVolume(100);
        mediaPlayer.mute(false);
        mediaPlayer.addMediaPlayerEventListener(new MediaPlayerEventListener() {

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void mediaChanged(MediaPlayer mediaPlayer, libvlc_media_t media, String mrl) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void opening(MediaPlayer mediaPlayer) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void buffering(MediaPlayer mediaPlayer, float newCache) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void playing(MediaPlayer mediaPlayer) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void paused(MediaPlayer mediaPlayer) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void stopped(MediaPlayer mediaPlayer) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void forward(MediaPlayer mediaPlayer) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void backward(MediaPlayer mediaPlayer) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void finished(MediaPlayer mediaPlayer) {
                Platform.runLater(new Runnable() {

                    @Override
                    @EnvelopeMethodProtectionAttributes(Protect = false)
                    public void run() {
                        mediaPlayer.setRate(1.0f);
                        cmbSpeed.getSelectionModel().select(0);
                        pauses.setVisible(true);
                        play.setVisible(false);
                        totalDurationValueLable.setText("");
                        durationRemaining.setText("");
//                playTime.setText("");
                        playerStop();
                    }
                });
            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void timeChanged(MediaPlayer mediaPlayer, long newTime) {
                Platform.runLater(new Runnable() {

                    @Override
                    @EnvelopeMethodProtectionAttributes(Protect = false)
                    public void run() {
                        seekSlider.setValue(newTime);
                    }
                });
            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void positionChanged(MediaPlayer mediaPlayer, float newPosition) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void seekableChanged(MediaPlayer mediaPlayer, int newSeekable) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void pausableChanged(MediaPlayer mediaPlayer, int newSeekable) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void titleChanged(MediaPlayer mediaPlayer, int newTitle) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void snapshotTaken(MediaPlayer mediaPlayer, String filename) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void lengthChanged(MediaPlayer mediaPlayer, long newLength) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void videoOutput(MediaPlayer mediaPlayer, int newCount) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void error(MediaPlayer mediaPlayer) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void mediaMetaChanged(MediaPlayer mediaPlayer, int metaType) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void mediaSubItemAdded(MediaPlayer mediaPlayer, libvlc_media_t subItem) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void mediaDurationChanged(MediaPlayer mediaPlayer, long newDuration) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void mediaParsedChanged(MediaPlayer mediaPlayer, int newStatus) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void mediaFreed(MediaPlayer mediaPlayer) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void mediaStateChanged(MediaPlayer mediaPlayer, int newState) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void newMedia(MediaPlayer mediaPlayer) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void subItemPlayed(MediaPlayer mediaPlayer, int subItemIndex) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void subItemFinished(MediaPlayer mediaPlayer, int subItemIndex) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void endOfSubItems(MediaPlayer mediaPlayer) {

            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void scrambledChanged(MediaPlayer mediaPlayer, int newScrambled) {
            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void elementaryStreamAdded(MediaPlayer mediaPlayer, int type, int id) {
            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void elementaryStreamDeleted(MediaPlayer mediaPlayer, int type, int id) {
            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void elementaryStreamSelected(MediaPlayer mediaPlayer, int type, int id) {
            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void mediaSubItemTreeAdded(MediaPlayer mp, libvlc_media_t l) {
            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void corked(MediaPlayer mp, boolean bln) {
                //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void muted(MediaPlayer mp, boolean bln) {
                //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void volumeChanged(MediaPlayer mp, float f) {
                //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void audioDeviceChanged(MediaPlayer mp, String string) {
                //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void chapterChanged(MediaPlayer mp, int i) {
                //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void mediaPlayerReady(MediaPlayer mp) {
                //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            @EnvelopeMethodProtectionAttributes(Protect = false)
            public void mediaParsedStatus(MediaPlayer mp, int i) {
                //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
}`

This is my code overview for initialising and playing video. 
I am calling the initMediaComponents() method from initialize() method of javafx controller.
In initMediaComponents()  I have created the media player instanc and the reference has been keept at class level. Still it is crashing. Please review my code and suggest me. I am badly need help, I am in big trouble.

**Comment by caprica** [comment]
If you run the code in this project, not your own code, does it work for you or does it fail the same way?

Maybe post your hotspot crash log.

Also, are you attempting to use vlcj inside some sort of web server container, I see "jetty" mentioned in your code? If so, do you have adequate protection for concurrent access? Do you have multiple vlcj media players in the same application?

**Comment by rahulaparajit79** [comment]
No, previously I was using jetty, but not now, I didn't rename the class.
And there are no hotspot crash log.
In Windows Event viewer it only shows JRE crashed due to a jna3212xxxxx.dll file in temp directory.

**Comment by caprica** [comment]
You will need to find out how to generate a hotspot crash log on Windows.

If you post a crash log I *might* be able to help you, but I can't help you by looking at the code you posted.
