### ISSUE TITLE
Version conflict in vlcj-javafx using JDK 1.8 and JavaFX 13

### ISSUE THREAD

**Issue by ingokreuz** [caprica/vlcj-javafx#25]
Hello Caprica

you state

> Java/JavaFX Versions
> This example project now requires JDK 1.8 and JavaFX 13 (for the new PixelBuffer).

This would be perfect because on my target systems java 8 is pre-installed.

I tried 
> adopt openJDK 8u232-b09 (hotspot)
 
together with 

> OpenJFX13.0.1

 and got the message

> Error:(22, 24) java: cannot access javafx.animation.Animation
>   bad class file: /D:/.../javafx-sdk-13.0.1/lib/javafx.graphics.jar!/javafx/animation/Animation.class
>     class file has wrong version 55.0, should be 52.0
>     Please remove or make sure it appears in the correct subdirectory of the classpath.
> 
(where line 22 in your example is
`import javafx.animation.Animation;`
)
In the ReleaseNotes on https://openjfx.io/ for version 13
(https://github.com/javafxports/openjdk-jfx/blob/jfx-13/doc-files/release-notes-13.md#release-notes-for-javafx-13)

you can find the following hint
> As of JDK 11 the JavaFX modules are delivered separately from the JDK. These release notes cover the standalone JavaFX 13 release. JavaFX 13 requires JDK 11 or later.

So how did you manage to use JavaFX13 together with Java8?

**Comment by caprica** [comment]
Likely this is simply a failure to keep documentation up to date.

The example in question requires whatever JDK that JavaFX 13 requires.

The other examples in this repository (that don't use PixelBuffer) should be fine with Java 8.

**Comment by caprica** [comment]
Seems Java 11 is required for JavaFX 13.

**Comment by ingokreuz** [comment]
Thank you for your quick answer. Yes I know the problem to keeping documentation up to date ;-) Too bad: I hoped you had a solution... In spring my company upgrades to Java 11...so I will wait until spring. Thank you again for your effort and for your great project. Ingo

**Comment by caprica** [comment]
Well, you could still use the other approach shown in this project without PixelBuffer if you need to target an earlier JDK. The performance won't be quite as good as with PixelBuffer but it's still pretty good.
