### ISSUE TITLE
No suitable constructor found for WritableImage

### ISSUE THREAD

**Issue by MarcWoodyard** [caprica/vlcj-javafx#27]
I'm getting the following error message below when I try to run WritableImageDemo.java.

**Error:**

> Error:(101, 26) java: no suitable constructor found for WritableImage(javafx.scene.image.PixelBuffer<java.nio.ByteBuffer>)
>     constructor javafx.scene.image.WritableImage.WritableImage(int,int) is not applicable
>       (actual and formal argument lists differ in length)
>     constructor javafx.scene.image.WritableImage.WritableImage(javafx.scene.image.PixelReader,int,int) is not applicable
>       (actual and formal argument lists differ in length)
>     constructor javafx.scene.image.WritableImage.WritableImage(javafx.scene.image.PixelReader,int,int,int,int) is not applicable
>       (actual and formal argument lists differ in length)

**Details:**
IDE: IntelliJ
OS: Ubuntu Linux
Java: openjdk version "11.0.5" 2019-10-15
JavaFX: Version 13.0.1

**WritableImage Java Doc:** https://openjfx.io/javadoc/13/javafx.graphics/javafx/scene/image/WritableImage.html

https://github.com/caprica/vlcj-javafx/blob/5dec95a1dff384a9c0a5d6ca37bcf2648454e7e7/src/test/java/uk/co/caprica/vlcj/javafx/test/WritableImageDemo.java#L140

**Comment by MarcWoodyard** [comment]
Just tested with openjdk version "13" 2019-09-17 and it still doesn't work.

**Comment by caprica** [comment]
Looks to me like you are not using JavaFX13 despite what you posted. In the javadoc you linked you can see the constructor the code is using is there.

**Comment by MarcWoodyard** [comment]
Looks like Intellij was acting weird. I just recreated the project and copied over the old lib folder and everything seems to work again.
