### ISSUE TITLE
VideoSurface not cleared after stopping the player

### ISSUE THREAD

**Issue by acely** [caprica/vlcj-javafx#4]
Hi, after calling `vlcplayer.controls().stop();` the video surface is not black, one video frame is still left in it.

Test Environment:

> System=macOSX 10.11
> JDK=11.0.15 by Jetbrains
> JavaFX=16
> VLC=4.0.0-dev-d7d51df0 (2022-07-09)
> vlcj & vlcj-javafx & vlcj-natives=git-latest@2022-07-10
> jna=5.12.1

**Comment by caprica** [comment]
The video surface is presented with every frame that VLC has decoded, if there is no black frame at the end of the video, you won't see a black frame in the ImageView buffer.

The solution for this is always to just wait for the finished/stopped event and switch the video view to whatever default view you want (can be a black rectangle or whatever).

In Swing you could use a CardLayout, in JavaFX I don't recall an equivalent component that could be used but there will be one.

**Comment by acely** [comment]
Ok I use the `stopped` event and works fine.
