### ISSUE TITLE
RandomAccessFileMedia has some error

### ISSUE THREAD

**Issue by Anivie** [caprica/vlcj-javafx#5]
Thank you for your great contribution to the javafx community!

I am trying to use RandomAccessFileMedia to play a video,it can greatly play then initially(but have a gc error),but,only 5seconds later,it print another gc error(the first two lines),and then it stop playing.

Using:`embeddedMediaPlayer.media().play(RandomAccessFileMedia(File("D:\\download\\Bilibili\\luo-master\\112.mp4")))`
Error:
```
JNA: callback object has been garbage collected
JNA: callback object has been garbage collected
[000001d705db8480] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001d7124f6580] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001d7124f4190] imem demux error: Invalid get/release function pointers
[000001d713acfc30] main vout display error: Failed to set on top
[000001d7139d0e50] main vout display error: Failed to set on top
[h264 @ 000001d7126ee8c0] Invalid NAL unit size (31197 > 29784).
[h264 @ 000001d7126ee8c0] Error splitting the input into NAL units.
[000001d7139e4c20] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001d7139e45e0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001d7139b7af0] imem demux error: Invalid get/release function pointers
```

An another question is,i am trying to write a class like this,but it can't work:
```kotlin
    class MediaVideo(private val inputStream: InputStream): DefaultCallbackMedia(true) {
        override fun onGetSize(): Long {
            return inputStream.available().toLong()
        }
        override fun onOpen(): Boolean {
            return true
        }
        override fun onRead(buffer: ByteArray?, bufferSize: Int): Int {
            return inputStream.read(buffer, 0, bufferSize)
        }
        override fun onSeek(offset: Long): Boolean {
            return true
        }
        override fun onClose() {
            inputStream.close()
        }
    }
```

Call him:`embeddedMediaPlayer.media().play(MediaVideo(FileInputStream("D:\\download\\Bilibili\\luo-master\\112.mp4")))`

It will print gc error in first time,and then nothing will be displayed.
error is:
```
JNA: callback object has been garbage collected
JNA: callback object has been garbage collected
[000002a9ceb18480] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000002a9db7d6580] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000002a9db7d4190] imem demux error: Invalid get/release function pointers
[000002a9db7db9e0] mp4 demux error: MP4 plugin discarded (no moov,foov,moof box)
[000002a9ceb14da0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000002a9ceb137c0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000002a9db833140] imem demux error: Invalid get/release function pointers
[000002a9db8d4630] mp4 demux error: MP4 plugin discarded (no moov,foov,moof box)
```
This video can be played using mrl on play() method.How can i fix it?

My jdk:zulu-jdk17
Javafx version:18.0.2
Os:windows 10 x64

**Comment by caprica** [comment]
This part is key:
```
JNA: callback object has been garbage collected
```
You must keep a hard-reference to your RandomAccessFileMedia object instance, the same as you must keep a hard reference to a MediaPlayer object instance, to prevent that object from being garbage collected.

How you keep that reference depends on how your code is organised.

**Comment by Anivie** [comment]
> This part is key:
> 
> ```
> JNA: callback object has been garbage collected
> ```
> 
> You must keep a hard-reference to your RandomAccessFileMedia object instance, the same as you must keep a hard reference to a MediaPlayer object instance, to prevent that object from being garbage collected.
> 
> How you keep that reference depends on how your code is organised.

I am using this to keep it hard reference:
```kotlin
        val video = MediaVideo(FileInputStream("D:\\download\\Bilibili\\luo-master\\112.mp4"))
        thread {
            while (true) {
                Thread.sleep(Long.MAX_VALUE)
                video
            }
        }
```
Do you have a better way?

And my MediaVideo class still doesn't work:
```
[000001ba78248480] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001ba053d6580] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001ba053d4190] imem demux error: Invalid get/release function pointers
[000001ba053db9e0] mp4 demux error: MP4 plugin discarded (no moov,foov,moof box)
```
But i can't find the error reason in it.Could you please tell me how can i fix it?

**Comment by caprica** [comment]
It might not be the media that gets garbage collected, it might be the media player itself. It's impossible to tell based on what you posted.

In terms of the specific code you showed, that loop and sleep is really not a good idea, just use Thread.currentThread().join(), but anyway that is not really causing your issue.

**Comment by Anivie** [comment]
> Thread.currentThread().join()

RandomAccessFileMedia can work greatly when i using this code,but my class still can't work.
And,how can i get full error message for you?
This is all my code:
```kotlin
    private val embeddedMediaPlayer = MediaPlayerFactory().mediaPlayers().newEmbeddedMediaPlayer()

    override val root = stackpane {
        val view = imageview {
            isPreserveRatio = true
        }
        embeddedMediaPlayer.videoSurface().set(ImageViewVideoSurface(view))

        val video = RandomAccessFileMedia(File("D:\\download\\Bilibili\\luo-master\\112.mp4"))
        thread {
            Thread.currentThread().join()
            video
        }
        embeddedMediaPlayer.media().play(video)
        //embeddedMediaPlayer.media().play(RandomAccessFileMedia(File("D:\\download\\Bilibili\\luo-master\\112.mp4")))//old way

        primaryStage.setOnCloseRequest {
            embeddedMediaPlayer.controls().stop()
            embeddedMediaPlayer.release()
        }
    }
```

**Comment by caprica** [comment]
I don't understand, what still doesn't work?

Because this code...

```
embeddedMediaPlayer.media().play(RandomAccessFileMedia(File("D:\\download\\Bilibili\\luo-master\\112.mp4")))//old way
```
...is simply wrong because nothing keeps a reference to the RandomAccessFileMedia that you have created, it goes out of scope immediately and will become garbage collected at some point.

Also, I have to ask, why are you not just using play("d:\\download...") - why are you using RandomAccessFile? The RandomAcecssFile is for a very specialised and unusual use-case.

**Comment by Anivie** [comment]
> I don't understand, what still doesn't work?
> 
> Because this code...
> 
> ```
> embeddedMediaPlayer.media().play(RandomAccessFileMedia(File("D:\\download\\Bilibili\\luo-master\\112.mp4")))//old way
> ```
> 
> ...is simply wrong because nothing keeps a reference to the RandomAccessFileMedia that you have created, it goes out of scope immediately and will become garbage collected at some point.
> 
> Also, I have to ask, why are you not just using play("d:\download...") - why are you using RandomAccessFile? The RandomAcecssFile is for a very specialised and unusual use-case.

Sorry I didn't fully describe my question.
My question is why the class MediaVideo written by me is still not working.
The reason I'm not using mrl is that I'm writing a web video app and I use okhttp to get the inputstream and try to play it in javafx. But this class didn't work.
Also, I found that when I use FileInputStreamMedia, the player doesn't work properly, but when I use RandomAccessFileMedia, he supports working (passed files are all the same).
FileInputStreamMedia get this error:
```
[000002c561e18460] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000002c56c966580] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000002c56c964190] imem demux error: Invalid get/release function pointers
[000002c56c969720] mp4 stream error: no moov before mdat and the stream is not seekable
[000002c56c968590] prefetch stream error: cannot seek (to offset 48)
[mov,mp4,m4a,3gp,3g2,mj2 @ 000002c56c9c1240] stream 0, offset 0x5db94: partial file
[000002c56ca86e40] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000002c56ca86800] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000002c56c9740c0] imem demux error: Invalid get/release function pointers
[000002c561e19230] mp4 stream error: no moov before mdat and the stream is not seekable
[000002c561e187b0] prefetch stream error: cannot seek (to offset 48)
[mov,mp4,m4a,3gp,3g2,mj2 @ 000002c56ca0d7c0] stream 0, offset 0x5db94: partial file
```

**Comment by caprica** [comment]
Instead of using OkHttp why not just play the HTTP URL directly? Using InputStreams is niche and not recommended.

**Comment by Anivie** [comment]
> Instead of using OkHttp why not just play the HTTP URL directly? Using streams is niche and not recommended.

Because i am trying to playing a video from a formal business website(like youtube),if  i am using a url to play it,it will have a bad http response(403),is there any better way in it?

**Comment by caprica** [comment]
Can the VLC application play video from your "formal business website"? If so, then VLC can, and without messing around with InputStreams etc.

If you can open an HTTP request to it, there should be no reason to use Java InputStreams or OkHttp - just open the streaming URL, as long as you provide the credentials. If you have to do custom security authentication, with custom headers/tokens or whatever, then yes, maybe that will be a problem.

**Comment by Anivie** [comment]
> Can the VLC application play video from your "formal business website"? If so, then VLC can, and without messing around with InputStreams etc.
> 
> If you can open an HTTP request to it, there should be no reason to use Java InputStreams or OkHttp - just open the streaming URL, as long as you provide the credentials. If you have to do custom security authentication, with custom headers/tokens or whatever, then yes, maybe that will be a problem.

Yes,it may be need a special request header,so i need a web frmework to visit it.
Do you have any way for it?Thanks for your guidance.

**Comment by caprica** [comment]
I think the original issue was resolved, if you still have another problem than create a new ticket rather than changing the topic of this one.
