### ISSUE TITLE
Provide alternative fullscreen strategy for JavaFX

### ISSUE THREAD

**Issue by schrepfler** [caprica/vlcj-javafx#6]
When using JavaFX one can get away without using any Swing components while initialising the app making the use of AdaptiveFullScreenStrategy(java.awt.Window) difficult without dragging Swing components into the application contex.

Provide an alternative strategy which does not rely on AWT being available explicitly.

**Comment by caprica** [comment]
With JavaFX, you use JavaFX functions to control full-screen via the Stage, IIRC.

You should not be using the fullscreen strategy classes at all with JavaFX.

**Comment by caprica** [comment]
It's literally this to toggle full-screen for a stage:
```
stage.setFullScreen(!stage.isFullScreen())
```
What more do you need from vlcj?

**Comment by schrepfler** [comment]
Hi @caprica, admittedly I'm using JavaFX so still figuring all the API surface. Wouldn't a Stage be a composite of many components? Isn't that different from showing only the video to a full-screen canvas (typical behaviour for double click on video on most video players).

**Comment by caprica** [comment]
Then you show/hide the other components in the stage when you toggle fullscreen.

The point is it does not need to be in the core vlcj API.

You might still be able to implement it via a FullScreenStrategy, I'm not sure.

**Comment by caprica** [comment]
It was trivial to add a new strategy, see https://github.com/caprica/vlcj-javafx/commit/07585835bea4b9f49cad636cf8b63b88579eb892.

You will be expected to provide the necessary custom behaviour in the `onBeforeEnterFullscreen` and `onAfterExitFullscreen` overrides, the same as in the other full-screen strategy implementations.

**Comment by caprica** [comment]
This will be delivered with the 1.2.0 release, which is already on its way to the Maven Central Repository.

**Comment by schrepfler** [comment]
Cool, thanks for the feedback anyhow!
