### ISSUE TITLE
Maven Repository Not Up to date

### ISSUE THREAD

**Issue by TVIL-Brainy** [caprica/vlcj-javafx#7]
Hi Mark, I'm playing with VLCJ library with JavaFX & I'm having some build issues.

I'm seeing "java.lang.NoClassDefFoundError: uk/co/caprica/vlcj/player/embedded/videosurface/callback/format/RV32BufferFormat" error with 1.2.0 version which seems to be fixed in current master branch. 

The maven repository is not updated since 2022-10-09 (https://central.sonatype.com/artifact/uk.co.caprica/vlcj-javafx/1.2.0/versions).

Could you push the current update to maven repository?

Thanks!.
Vijay

**Comment by caprica** [comment]
IIRC this was renamed to StandardOpaqueBufferFormat

**Comment by caprica** [comment]
Also, I think there are newer snapshot releases available if you enable snapshot repos.

**Comment by TVIL-Brainy** [comment]
Thanks Mark. Enabling snapshot repos in pom.xml & using 1.2.1-SNAPSHOT worked!

**Comment by caprica** [comment]
Obviously there'll be a full release at some point. The real blocker is waiting for VLC 4.0.0 to be honest.
