### ISSUE TITLE
Missing Artifact

### ISSUE THREAD

**Issue by Pavan-MV17** [caprica/vlcj-javafx#8]
Hi Mark, I'm playing with VLCJ library with JavaFX & I'm having some build issues.

I'm seeing "Missing artifact uk.co.caprica:vlcj:jar:5.0.0-snapshots"

Could you push the current update?

Thanks!
Pavan M V

**Comment by Pavan-MV17** [comment]
I'm seeing this "uk\co\caprica\vlcj\javafx\fullscreen\JavaFXFullScreenStrategy error: package javafx.stage does not exist" error with 4.7.3 version

**Comment by caprica** [comment]
Recent snapshots are already available in the Maven snapshot repo, or the github project if you add that as a snapshot repo.

But you must enable snapshot repos in your own workspace pom.xml.

**Comment by Pavan-MV17** [comment]
Where do I find the recent snapshots?

**Comment by caprica** [comment]
I already said, in the Maven snapshot repo. So if you're using maven, or gradle, or whatever other build tool, enable snapshot repos and it will automatically find them for you.

As to how to do that, that is out of scope, you can find plenty guides to do it or ask an AI or whatever.

**Comment by Pavan-MV17** [comment]
Thank you!

**Comment by caprica** [comment]
Actually, I had forgotten and this just reminded me, there is this build available:

```
<dependency>
    <groupId>uk.co.caprica</groupId>
    <artifactId>vlcj</artifactId>
    <version>5.0.0-M1</version>
</dependency>
```

https://central.sonatype.com/artifact/uk.co.caprica/vlcj/5.0.0-M1
